### ISSUE TITLE
Remove JAX omnistaging warning

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aesara#1001]
JAX version 0.2.12 was released in April 2021

```
UserWarning: JAX omnistaging couldn't be disabled: Disabling of omnistaging is no longer supported in JAX version 0.2.12 and higher: see https://github.com/google/jax/blob/main/design_notes/omnistaging.md.
  warnings.warn(f"JAX omnistaging couldn't be disabled: {e}
```

**Comment by rlouf** [comment]
Following the discussion in #1014 I think we should remove this warning, but fail graciously whenever we _know_ that JAX will raise.

**Comment by brandonwillard** [comment]
> Following the discussion in #1014 I think we should remove this warning, but fail graciously whenever we _know_ that JAX will raise.

Yeah, let's do that.
