### ISSUE TITLE
Numpy warnings should be filtered more precisely

### ISSUE THREAD

**Issue by maresb** [aesara-devs/aesara#1005]
Numpy emits some false-positive warnings which we should filter. In #980 we filter messages which were previously being missed. But while examining the code, we noticed that the current filtering may be too aggressive in some places.

[Here](https://github.com/aesara-devs/aesara/blob/d6858fe23af29cb28379723175895c9d02fdca51/aesara/link/c/cmodule.py#L2722) we do

```python
numpy.distutils.system_info.system_info.verbosity = 0
```

but we don't set it back to the original value. This could lead to side-effects.

Also, the previous line

```python
with warnings.catch_warnings(record=True):
```

fails to capture certain warnings (hence the need for #980), and it's not clear to me which messages, if any, it is actually filtering out.

It would be nice to

1. understand/document/test the function of these two lines
2. ensure that these lines don't filter out true-positive warnings, or cause side-effects in Aesara or downstream.

**Comment by brandonwillard** [comment]
Is this still an issue?

**Comment by maresb** [comment]
Nope! Now that

```python
numpy.distutils.system_info.system_info.verbosity = 0
```

is gone, I no longer see any problem.

Indeed, another reason your workaround was cleaner than mine: it was somehow immune to the latest setuptools catastrophe. :smile:
