### ISSUE TITLE
Missing numba implementation of expit

### ISSUE THREAD

**Issue by aseyboldt** [aesara-devs/aesara#1022]
## Description of your problem or feature request

In numba mode, we can't compile functions that contain sigmoid operations:

```python
import aesara.tensor as at
from scipy import special
import numba

x = at.dvector("x")
y = at.sigmoid(x)
func = aesara.function([x], y, mode="NUMBA")  # Fails in numba compilation

# Because this isn't implemented
@numba.njit
def foo(x):
    return special.expit(x)

foo(0.1)
```

## Versions and main components

* Aesara version d09e222b06 (current main)

**Comment by ricardoV94** [comment]
@aseyboldt this was already solved, right?

**Comment by aseyboldt** [comment]
Yes it is, forgot to close or link the issue
