### ISSUE TITLE
Remove `CholeskyGrad` Op

### ISSUE THREAD

**Issue by purna135** [aesara-devs/aesara#1098]
I'm wondering if we should remove the [CholeskyGrad](https://github.com/aesara-devs/aesara/blob/main/aesara/tensor/slinalg.py#L126-L190) Op entirely because we have a working [L_Op](https://github.com/aesara-devs/aesara/blob/main/aesara/tensor/slinalg.py#L70) inside the `Cholesky` Op and are no longer using `CholeskyGrad` Op.

Thanks to @ricardoV94 for sharing this reference (https://github.com/aesara-devs/aesara/commit/1c8f8d6ace92683359ef74401e57a7b09a209f7e), which shows that `CholeskyGrad` was used in the original implementation of `Cholesky` but was later removed.

**Comment by brandonwillard** [comment]
Yes, we should remove it.

**Comment by sudarsan2k5** [comment]
Hi, I would like to work on this.

**Comment by brandonwillard** [comment]
> Hi, I am a beginner to opensource and I guess it's a beginner friendly issue so I would like to work on this.

No problem; take a look at the [developer start guide](https://aesara.readthedocs.io/en/latest/dev_start_guide.html) and feel free to submit a PR.  If you have questions, we're on [Gitter](https://gitter.im/aesara-devs/aesara) or you can open a [Discussion](https://github.com/aesara-devs/aesara/discussions).
