### ISSUE TITLE
DefaultRandomState is not updated in .eval

### ISSUE THREAD

**Issue by ferrine** [aesara-devs/aesara#1114]
## Description of your problem
Not sure if it is the desired behaviour or just a bug

```python
r = at.random.uniform(size=10)
print(r.eval())
print(r.eval())
```
<img width="592" alt="image" src="https://user-images.githubusercontent.com/11705326/184608564-84dd5181-156d-4fa7-adbf-8393d6c08b1d.png">

I noticed that when I use non-default rng, this works as I expect it to
<img width="652" alt="image" src="https://user-images.githubusercontent.com/11705326/184608748-d1d06529-8185-4c0c-a184-271c38154037.png">

**Comment by ricardoV94** [comment]
`RandomStream` sets default_updates of RandomVariables created with it. Otherwise you have to do it manually:

```python
r = at.random.uniform(size=10)
prev_rng = r.owner.inputs[0]
next_rng = r.owner.outputs[0]
prev_rng.default_update = next_rng
print(r.eval())
print(r.eval())

# Or
f = aesara.function([], r, updates={prev_rng: next_rng})
print(f())
print(f())
```
