### ISSUE TITLE
`ChoiceRV`'s behavior also differs from NumPy's `choice`

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aesara#1146]
`ChoiceRV`'s behavior differs from NumPy's `choice` in that it does not accept input tensors that have more than one dimension while NumPy does. The following raises an error in Aesara:

```python
import aesara.tensor as at
import numpy as np

arr = np.vstack([[1,2], [3,4]])
srng = at.random.RandomStream(0)
c_rv = srng.choice(at.as_tensor(arr))
print(c_rv.eval())
```

while this does not:

```python
import numpy as np

arr = np.vstack([[1,2], [3, 4]])
rng = np.random.default_rng()
print(rng.choice(arr))
# [3,, 4]
```

I could not find an explanation for this anywhere in the codebase, although it seems that this was intentional as the tests explicitly test for the above example raising an exception. If you can think of a specific reason for this behavior I will document it, otherwise I will change it to follow NumPy's.

_Originally posted by @rlouf in https://github.com/aesara-devs/aesara/issues/1105#issuecomment-1218334644_

**Comment by brandonwillard** [comment]
Is the second example supposed to be using NumPy instead of Aesara?

**Comment by rlouf** [comment]
Yes, sorry, I corrected the example.
