### ISSUE TITLE
Compile `Mode`s still uses "optimize" instead of "rewrite"

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aesara#1167]
For example:

https://github.com/aesara-devs/aesara/blob/e40c827462ff2956010794ac94a38e70ae3a3131/aesara/compile/mode.py#L304

**Comment by brandonwillard** [comment]
Yeah, this one might be permissable, because, at this level, the rewrites are actually expected to optimize something (e.g. certain aspects of performance).

**Comment by rlouf** [comment]
Makes sense. Closing.
