### ISSUE TITLE
Mypy cannot determine type of `op_debug_information`

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#1221]
MyPy run by `pre-commit` will occasionally err with the following:
```
aesara/scan/op.py:3443: error: Cannot determine type of "op_debug_information"  [has-type]
Found 1 error in 1 file (checked 1 source file)
```

This issue appears to be due to differences in command-line module ordering (see https://github.com/pre-commit/pre-commit/issues/1580#issuecomment-679413936, https://github.com/pypa/pip/issues/9502#issue-792721417, and https://github.com/python/mypy/issues/9954).

Let's see if we can remove this ordering disparity, because it's awfully annoying.

**Comment by brandonwillard** [comment]
@LegrandNico and @markusschmaus, have either of you run into this before?  If so, have any ideas?

**Comment by LegrandNico** [comment]
I cannot reproduce the error on my side, both mypy and pre-commit are running correctly, but this could be due to pre-commit virtual env not updating correctly for some reason. I experienced something similar with typing extensions and I had to delete the pre-commit env folder to re-install it.

**Comment by brandonwillard** [comment]
> I cannot reproduce the error on my side, both mypy and pre-commit are running correctly, but this could be due to pre-commit virtual env not updating correctly for some reason. I experienced something similar with typing extensions and I had to delete the pre-commit env folder to re-install it.

Yeah, it's not consistent for me either, which is what makes this so challenging.

**Comment by ricardoV94** [comment]
I get this error every single time. I've tried to clear the cache / reinstall pre-commit without success.
