### ISSUE TITLE
Update time.clock() to time.perf_counter() in documentation under tutorial/conditions 

### ISSUE THREAD

**Issue by laurennoell** [aesara-devs/aesara#1292]
On the webpage https://aesara.readthedocs.io/en/latest/tutorial/conditions.html#ifelse-vs-switch,
the code example uses time.clock() which is deprecated as of python 3.3. I believe it should be updated to time.perf_counter().

The block of code in question currently looks like this:

```python

tic = time.clock()
for i in range(n_times):
    f_switch(val1, val2, big_mat1, big_mat2)
print('time spent evaluating both values %f sec' % (time.clock() - tic))

tic = time.clock()
for i in range(n_times):
    f_lazyifelse(val1, val2, big_mat1, big_mat2)
print('time spent evaluating one value %f sec' % (time.clock() - tic))

```
every time.clock() instance should be updated to time.perf_counter() so like this:

```python
tic = time.perf_counter()
for i in range(n_times):
    f_switch(val1, val2, big_mat1, big_mat2)
print('time spent evaluating both values %f sec' % (time.perf_counter() - tic))

tic = time.perf_counter()
for i in range(n_times):
    f_lazyifelse(val1, val2, big_mat1, big_mat2)
print('time spent evaluating one value %f sec' % (time.perf_counter() - tic))
```

As far as I can tell, this is the only instance of time.clock() used in the documentation.

**Comment by brandonwillard** [comment]
Thanks for the heads-up!  We've been in the process of fixing these `time` uses in our old code, but I don't think we noticed this instance.
