### ISSUE TITLE
Failing nightly build

### ISSUE THREAD

**Issue by maresb** [aesara-devs/aesara#1379]
Success on [Dec. 28](https://github.com/aesara-devs/aesara/actions/runs/3790978838/jobs/6446051005) and failure on [Dec. 29](https://github.com/aesara-devs/aesara/actions/runs/3797620542/jobs/6458717648), and the corresponding [diff on main](https://github.com/aesara-devs/aesara/compare/e9bd02684e4cb7c0f01cb6ec9d30c511057812e7..f874925fecabd50a751d82c6d8a9aad41ce1acbe).

The problem seems to be that the nightly package is being built as `aesara` instead of `aesara-nightly`. Perhaps `pyproject.toml` is overriding `setup.py` when `python -m build --sdist .` is run.

**Comment by maresb** [comment]
Ok, I think I see roughly what's going on. Without having gone fully into the source code, I'm fairly confident that what's going on is the `build` module is mocking the `setuptools.setup` function to get the dependencies as defined programmatically in `setup.py`, but it's discarding the `name` kwargument which we are relying on for the `aesara-nightly` name.

**Comment by maresb** [comment]
I see two obvious solutions:

1. Revert from `python -m build --sdist .` to `python setup.py sdist`.
2. Update `nightly.yml` as per #1375.

I'd vote for 2. since it's more forward-looking.

**Comment by maresb** [comment]
The nightly build succeeded, and so now I was able to diff the old/new sdists from PyPI.

Notable differences:

1. `aesara/_version.py` now has `"dirty": true` instead of `false` because `pyproject.toml` was modified before build.
2. In `PKG-INFO`, the `Author: aesara-devs` and `Author-email: aesara.devs@gmail.com` have been merged into `Author-email: aesara-devs <aesara.devs@gmail.com>`. Also, the `Home-page:` key has been replaced by `Project-URL: Homepage, `. This all seems to be in order according to the [core metadata specification](https://packaging.python.org/en/latest/specifications/core-metadata/).

This seems to be a total success, and a good check in preparation for #1375. I want to do a few more checks and I think we can merge that.

**Comment by brandonwillard** [comment]
> This seems to be a total success, and a good check in preparation for #1375. I want to do a few more checks and I think we can merge that.

It does; that's awesome!  Feel free to merge that PR whenever you want.

**Comment by maresb** [comment]
Thanks!!!

Some things regarding Python packaging seemingly cannot be understood...

For whatever reason, `python -m build .` generates a directory called `aesara.egg-info` containing, among other things, a file called `SOURCES.txt`. This is a list of files which get included in the resulting sdist. It seems that the `build` command does not refresh this file. Thus when rendering locally and not on a fresh clone, I was seeing the wrong files being bundled.

*Conclusion:* when testing local builds, always run `rm -rf aesara.egg-info && python -m build .`.

(This makes me wonder about the previous migration to `setup.cfg`: a bunch of C files were missing (#1182), but I was sure I had triple-checked everything and that the correct files were being bundled. Maybe this explains why there were missing files even though I checked... or maybe I just had an oversight. :laughing:)

Maybe I should open an issue on `build`. (For reference, I'm using v0.9.0.)
