### ISSUE TITLE
Math typo in logistic sigmoid function docstring

### ISSUE THREAD

**Issue by larryshamalama** [aesara-devs/aesara#1401]
There are three docstring instances where the sigmoid/expit function is incorrectly displayed as `(1 / (1 + exp(x))` instead of `(1 / (1 + exp(-x))`.

https://github.com/aesara-devs/aesara/blob/2dc759127547d4b836629e927b7af24f840cc91c/aesara/tensor/inplace.py#L318

https://github.com/aesara-devs/aesara/blob/baa6b7fa3f5ba53359bf1180260b0afb6b924287/aesara/tensor/math.py#L1421

https://github.com/aesara-devs/aesara/blob/a7ef6db7535c60911446930b12f35d986c2e0094/aesara/scalar/math.py#L1093

**Comment by brandonwillard** [comment]
Thanks for the heads-up!

**Comment by kushalnl7** [comment]
Hi, I would like to solve this issue!

**Comment by vrii14** [comment]
I will solve this issue

**Comment by vrii14** [comment]
I have raised the PR for this issue - #1402. Please review the same

**Comment by brandonwillard** [comment]
Many thanks, @vrii14!
