### ISSUE TITLE
Nightly version numbering issue after package metadata changes

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#1406]
Looks like we need some additional changes to address [this dev version issue during the nightly build](https://github.com/aesara-devs/aesara/actions/runs/4094517974/jobs/7060780835#step:7:31).  We can temporarily revert https://github.com/aesara-devs/aesara/pull/1405 in the meantime, if need be.

**Comment by maresb** [comment]
Ah, ok, I think this is independent of #1405. Hatchling uses `setuptools_scm` indirectly via the `hatch-vcs` plugin, so I suspect that some arguments aren't being passed through. I'll take a quick look to see if it's something obvious...
