### ISSUE TITLE
"error in pydot2 setup command: use_2to3 is invalid" while installing requirements-rtd.txt dependencies

### ISSUE THREAD

**Issue by Ankit-Dhankhar** [aesara-devs/aesara#1488]
## Description of your problem or feature request

While setting up Aesaro from latest commit (`3eb7cdfaa7b97c9791d8303ae440a5f141c6d813`) by following this [guide] (https://aesara.readthedocs.io/en/latest/dev_start_guide.html). On running `pip install -r requirements-rtd.txt` following error is thrown:

```
Obtaining file:///home/ankit/Desktop/Github/Aesara (from -r requirements-rtd.txt (line 1))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: sphinx>=1.3.0 in /home/ankit/miniconda3/envs/aesara-dev/lib/python3.10/site-packages (from -r requirements-rtd.txt (line 2)) (6.1.3)
Collecting sphinx-book-theme
  Using cached sphinx_book_theme-1.0.1-py3-none-any.whl (396 kB)
Collecting sphinx-design
  Using cached sphinx_design-0.3.0-py3-none-any.whl (2.2 MB)
Collecting jinja2<3.1.0
  Using cached Jinja2-3.0.3-py3-none-any.whl (133 kB)
Requirement already satisfied: pygments in /home/ankit/miniconda3/envs/aesara-dev/lib/python3.10/site-packages (from -r requirements-rtd.txt (line 6)) (2.14.0)
Requirement already satisfied: pytest in /home/ankit/miniconda3/envs/aesara-dev/lib/python3.10/site-packages (from -r requirements-rtd.txt (line 7)) (7.2.2)
Requirement already satisfied: numpy in /home/ankit/miniconda3/envs/aesara-dev/lib/python3.10/site-packages (from -r requirements-rtd.txt (line 8)) (1.22.4)
Collecting gnumpy
  Using cached gnumpy-0.2.tar.gz (28 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pydot in /home/ankit/miniconda3/envs/aesara-dev/lib/python3.10/site-packages (from -r requirements-rtd.txt (line 10)) (1.4.2)
Collecting pydot2
  Using cached pydot2-1.0.33.tar.gz (19 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in pydot2 setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Same issue can be reproduced by running `pip install pydot2`

This issue is previously reported in [this](https://github.com/aesara-devs/aesara/issues/1263#issuecomment-12809888260) and [this](https://github.com/aesara-devs/aesara/discussions/1459#discussion-4906904) discussion thread which was fixed by removing pydot2 from `requirement-rtd.txt` and pinning the version of sepuptools to older version (latest in this case v67.6.1) respectively.

## Versions and main components

* Aesara version: git commit - 3eb7cdfaa7b97c9791d8303ae440a5f141c6d813
* Python version: Python 3.10.10
* Operating system: GNU/Linux
* How did you install Aesara: (git + conda) by following this [guide] (https://aesara.readthedocs.io/en/latest/dev_start_guide.html)

Opening this issue to start discussion for the holistic solution of above issue.
- solution 1 (preferred) : Removed dependency from `pydot2` in `requirement-rtd.txt` 
- solution 2 : Add a message in [guide] (https://aesara.readthedocs.io/en/latest/dev_start_guide.html) to pin the version of setuptool to older version.

I would be glad to submit the PR for fixing this issue.

**Comment by brandonwillard** [comment]
> I would be glad to submit the PR for fixing this issue.

That would be great, thanks!
