### ISSUE TITLE
Implement vector-proof Softmax function

### ISSUE THREAD

**Issue by AlexAndorra** [aesara-devs/aesara#183]
## Description
_Originally reported by @ricardoV94 [here](https://github.com/pymc-devs/pymc3/pull/4229)_

Currently, `tt.nnet.softmax` raises `UserWarning: DEPRECATION: If x is a vector, Softmax will not automatically pad x anymore in next releases. If you need it, please do it manually. The vector case is gonna be supported soon and the output will be a vector.` in two places:

- https://github.com/pymc-devs/Theano-PyMC/blob/a9275c3dcc998c8cca5719037e493809b23422ff/theano/tensor/nnet/nnet.py#L443
- https://github.com/pymc-devs/Theano-PyMC/blob/a9275c3dcc998c8cca5719037e493809b23422ff/theano/tensor/nnet/nnet.py#L641

We actually use a custom version of Softmax in the PyMC3 codebase, to go around this limitation: https://github.com/pymc-devs/pymc3/blob/a05684b9588208882db164be113954eb21604ea1/pymc3/distributions/transforms.py#L463

```python
    def backward(self, y_):
        y = y_.T
        y = tt.concatenate([y, -tt.sum(y, 0, keepdims=True)])
        # "softmax" with vector support and no deprication warning:
        e_y = tt.exp(y - tt.max(y, 0, keepdims=True)) <-- this is the important line
        x = e_y / tt.sum(e_y, 0, keepdims=True) <-- this is the important line
        return floatX(x.T)
```

## Action to take

Assuming they indeed do the same things, we should probably **replace the current Theano implementation of the Softmax by the custom one we use in PyMC3**, thus getting a more robust implementation and taking care of the warning 🎉 

## Versions and main components

* Theano-PyMC 1.0.11.

**Comment by ricardoV94** [comment]
In addition, it might be helpful to implement a more flexible softmax function that also accepts the axis argument

**Comment by dfm** [comment]
Another option might be to just remove the warning unless someone has plans to remove this support? It looks like that warning was added 3 years, but I don't think anything has been done since then to remove this support.

**Comment by katosh** [comment]
The warning may not be misplaced. `tt.nnet.softmax` behaves as if `axis=1` is passed and this should not work on vectors. To fix this, the operation pads a `(1,)` to the left of the vector shape:
https://github.com/pymc-devs/Theano-PyMC/blob/a9275c3dcc998c8cca5719037e493809b23422ff/theano/tensor/nnet/nnet.py#L448
and the result of the operations has a shape that may be surprising:
```
>>> tt.nnet.softmax(np.array([1.,2])).eval().shape
(1, 2)
```
So the user is asked to make the operation unambiguous by changing the vector such that the softmax can be applied along `axis=1`.

I find the only good solution would be to implement support for the axis argument as @ricardoV94 suggested. But this requires a more profound understanding of the theano implementation than I currently have.

**Comment by AlexAndorra** [comment]
IIUC, the clearly best solution would be to refactor the current Theano implementation to make it work with an `axis` kwarg and set this to default to 0. But you seem to imply that it's difficult to do so @katosh ?

As a fallback option, would replace the current implementation by the one below (that we use in the PyMC3 code base as you know) be a good solution?

```python
# "softmax" with vector support and no deprication warning:
e_y = tt.exp(y - tt.max(y, 0, keepdims=True))
x = e_y / tt.sum(e_y, 0, keepdims=True)
```

**Comment by dfm** [comment]
I don't think there's a fundamental reason why using an implementation like that is a bad idea (there's nothing fancy happening in the current implementation! It looks like using BLAS commands was considered then commented out...) but there might be some performance hit depending on how well theano fuses non-elemwise ops. The other catch is that I don't think it makes sense to *just* replace this one op when all the other ops in that submodule have the same semantics.

**Comment by ricardoV94** [comment]
Any further thoughts on what might be a good strategy here? 
1. Write a more flexible version in the math module of pymc3
2. Rewrite the Theano implementation
3. Rewrite the Theano implementation + Other functions in that module which share the same axis 1 logic
4. Leave things as they are (including duplicated code in the pymc3 library)

.1. sounds like the most straightforward 
.2. and 3. require more care to make sure we are not breaking or slowing down important things

**Comment by AlexAndorra** [comment]
Yeah I'd go with 2 or 3 -- @brandonwillard is pretty adamant that 1 is kicking the can down the road, and I agree. Plus, we should take the opportunity of this Theano reformatting to do that 🤷‍♂️

3 is more involved though, so, depending on the experience of the person making the PR, it could be good to start by 2, and then complete with the rest of the module (i.e 3) once the process is clear
