### ISSUE TITLE
Add new Scan Op utils

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#19]
Let's consider adding the `Scan` utilities from https://github.com/pymc-devs/symbolic-pymc/pull/114 (e.g. the improved `ScanArgs` class and `convert_outer_out_to_in` function).

These would also help with a much needed general refactoring and simplification of `Scan`.

**Comment by ricardoV94** [comment]
The ScanArgs was already introduced. 

You mentioned a `convert_outer_out_to_in` function, is that still relevant?

**Comment by brandonwillard** [comment]
> You mentioned a `convert_outer_out_to_in` function, is that still missing/relevant?

It's in the `Scan` PR in AePLL, but doesn't really need to be in this repo at the moment.
