### ISSUE TITLE
Add tutorial on how to write new JAX implementations for new OPs

### ISSUE THREAD

**Issue by twiecki** [aesara-devs/aesara#230]
To make it easier for new contributors to add JAX implementations, we should have a small NB that gives an example.

**Comment by brandonwillard** [comment]
We have this as an RST doc (via #253), but I don't think it's accessible via https://aesara.readthedocs.io/, so we might need to change that.

**Comment by ricardoV94** [comment]
Is this still relevant? The rst JAX tutorial is visible on the docs
