### ISSUE TITLE
Remove static `Op` list in `aesara.tensor.basic.Alloc.do_constant_folding`

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#282]
These `Op`s should instead register themselves to a no-`Alloc`-constant-folding collection/class (e.g. using [`ABC.register`](https://docs.python.org/3/library/abc.html#abc.ABCMeta.register)).  This would prevent the need to reference/import classes from other modules within a base module like `aesara.tensor.basic`.  It would also make the functionality generally extensible in the first place.

**Comment by kc611** [comment]
Clone of #645. Discussion continued over there.
