### ISSUE TITLE
Flood of filelock warnings

### ISSUE THREAD

**Issue by twiecki** [aesara-devs/aesara#323]
Running a normal PyMC3 model and getting a ton of:

```
INFO:filelock:Lock 140695035376688 released on /Users/twiecki/.aesara/compiledir_macOS-10.15.6-x86_64-i386-64bit-i386-3.8.5-64/.lock
```

Already ran `aesara-cache clear` which didn't help.

**Comment by brandonwillard** [comment]
I don't think those are warnings, just overly verbose logging.

**Comment by brandonwillard** [comment]
Yes, those are log messages [emitted by `filelock`](https://github.com/benediktschmitt/py-filelock/blob/b30bdc4fb998f5f4350257235eb51147f9e81862/filelock.py#L274).
