### ISSUE TITLE
Replace handwritten MRG sampler

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#324]
The handwritten MRG sampler in `aesara.sandbox.rng_mrg` seems unnecessary.  It also doesn't use the `aesara.tensor.random` API, which causes it to require special attention in order to stay compatible, well tested, etc.

If we want to improve sampling performance, we should at least provide `RandomVariable`s with C implementations via the [NumPy C API](https://numpy.org/devdocs/reference/random/c-api.html) before resorting to a custom RNG implementation.  Also, MRG isn't exactly the best choice, and NumPy provides more/better choices.

**Comment by kc611** [comment]
Is there a reason for which this MRG sampler is preferred as default instead of using `numpy.random.RandomState`  and it's methods ?

( as seen in the issue here #322 )

**Comment by brandonwillard** [comment]
> Is there a reason for which this MRG sampler is preferred as default ( for ADVI ) instead of using `numpy.random.RandomState` and it's methods ?

I'm guessing that there are/were some relative performance advantages to using this MRG sampler, but I don't know if that's really/still true.  Plus, I would be rather surprised to find that this MRG implementation could notably outperform NumPy's (old and/or new) especially when the latter is accessed via its C API.

Otherwise, there are some comments implying that this implementation may be GPU ready/compatible, so perhaps that is/was the main appeal.

**Comment by kc611** [comment]
Alright so here, can we can turn `mrg_rng` into a wrapper class around `numpy.random.Randomstate` with it's own state stored inside the class ? We can then simply turn the c-code functions into ones accessing `numpy.random.Randomstate` via the C API.

The only downside of this I can think of is it's JAX conversion ( `jax.random` basically ) does not support most of the distributions currently defined inside `mrg_rng` for instance `multinomial` or `truncated_normal`

**Comment by brandonwillard** [comment]
It's starting to look like we should abandon our current `RandomState`/`RandomStateType`-centric approach in the first place.  

I don't see why we couldn't use an array-based state&mdash;like this MRG sampler and JAX&mdash;and perhaps support `RandomState` by converting _it_ to the array-form upfront, instead of the other way around, as we're currently doing.  This approach has the added benefit of simplifying our codebase, because we could remove `RandomStateType` and everything associated with it, since the array-form RNG state is already supported (because it's just an array)&mdash;and very efficiently at that!

If the new NumPy random API uses states that are closer to the form(s) used by the MRG sampler and JAX, then we should _definitely_ make this change; otherwise, if the new NumPy API is incompatible with this approach, then we shouldn't.

**Comment by rlouf** [comment]
Should we deprecate this?

**Comment by brandonwillard** [comment]
> Should we deprecate this?

The `rng_mrg`?  If so, yeah.
