### ISSUE TITLE
Stop using deprecated numpy aliases of builtin types

### ISSUE THREAD

**Issue by michaelosthege** [aesara-devs/aesara#325]
## Description of your problem or feature request

NumPy `v1.20` deprecated types like `np.bool`, `np.int` that are just aliases of builtins.
See https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In the `Cast` `Op` we're running into this deprecation warning: https://github.com/pymc-devs/aesara/blob/65c410b08f971313df24312a52dfce31d20ece72/aesara/scalar/basic.py#L2416

```python
\scalar\basic.py:2412: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    self.ctor = getattr(np, o_type.dtype)
```

We'll need to find a way to prioritize using the builtins over the aliases from NumPy.

## Versions and main components
* Aesara version: `theano-pymc 1.1.2` and latest `master`
* Python version: irrelevant
* Operating system: irrelevant

**Comment by brandonwillard** [comment]
While these have been remove from Aesara, they're still present in one of the external Python GPU dependencies (`pygpu`, I believe), so anyone loading those will see similar warnings when Aesara loads those libraries.
