### ISSUE TITLE
Change import aesara.tensor as aet to at

### ISSUE THREAD

**Issue by twiecki** [aesara-devs/aesara#328]
We decided on `import aesara.tensor as aet` but I think it should be `import aesara.tensor as at`. The reason is that the extra character isn't fun to look at for longer math expressions:
`aet.exp(aet.pow(aet.dot()))`
`at.exp(at.pow(at.dot()))`

With that it would also match `np`, `sp`, and the old `tt`.

**Comment by brandonwillard** [comment]
I agree.

**Comment by ricardoV94** [comment]
+ 1

**Comment by twiecki** [comment]
@brandonwillard still want to do this?

**Comment by brandonwillard** [comment]
> @brandonwillard still want to do this?

I'm not against it.
