### ISSUE TITLE
Numerical stabilization for log1mexp

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aesara#360]
We have a manual implementation on the PyMC side that stabilizes the operation `log(1 - exp(x))` by switching between `log1p` and `expm1` depending on where x lies:
 https://github.com/ricardoV94/pymc3/blob/d7f82a85dce9e0874f73dd6d48b096d5f8792313/pymc3/math.py#L221

This could be a simple and nice automatic rewrite to add to aesara that users could benefit from. It appears frequently when working with log cdfs for instance.

What would it require? Implementing a specific OP would be straightforward. But do we even need it or can rewrites just change one expression for another?

PS: I don't think aesara already does this one, but I will double check.

**Comment by twiecki** [comment]
@ricardoV94 Yes, that's an optimization we can (and should) easily add.

**Comment by ricardoV94** [comment]
Does it make sense to add a specific Op for these rewrites (it would be the similar in nature to the softplus)?

**Comment by twiecki** [comment]
What's the advantage over an optimization?

**Comment by ricardoV94** [comment]
It's not instead of the optimization. It would appear as a single op at the output of such optimization. The same way that if you have `exp(log(x) + 1)` it gets converted to a `softplus(x)`.

What are the advantages? I am not completely sure. I guess we can more easily target it in further optimizations (e.g., to undo it), otherwise we will just have a strange looking `tt.switch` floating around. Users can also use it directly (e.g., we are using it in half a dozen logp/logcdf methods in our pymc codebase).

The disadvantage is that we have one more core op to think about during rewrites.

Overall, I am pretty unsure what is the best apprach.

**Comment by twiecki** [comment]
Sounds like a new `Op` has more benefits and almost no downside.

**Comment by brandonwillard** [comment]
Yeah, we can create a new `Op` for this.
