### ISSUE TITLE
Add an option to skip type filtering during function evaluation

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#361]
When evaluating a function compiled with `aesara.function`, the arguments are filtered and type checked during every call (see [here](https://github.com/pymc-devs/aesara/blob/06c179267ed26b365090760a1c7d4239b7153d85/aesara/compile/function/types.py#L861)).  In some cases, this overhead is unnecessary (e.g. tight loops with well controlled inputs), so we should provide an option to skip that step.

N.B.: We'll need to do a side-by-side performance comparison of this, as well.

**Comment by sambhavsaxena** [comment]
I would like to work on this issue. 
Kindly guide me through..

**Comment by brandonwillard** [comment]
It should be as simple as adding a user-level option (i.e. via the `aesara.function` interface) and an `if` condition skipping the `filter` in the line linked above.

The most involved part will likely be the new test that goes along with this feature and some out-of-repo benchmarks in the PR, but that shouldn't be too difficult either.

**Comment by ricardoV94** [comment]
Is this different than the `trust_input` option?

**Comment by ricardoV94** [comment]
At least in the part of the code you linked to, setting `trust_input` to true skips the filtering.

However, I don't think `trust_input` is available as a keyword when creating the function so it's not very discoverable.

**Comment by brandonwillard** [comment]
Yes, `Function.trust_input` accomplishes this.
