### ISSUE TITLE
Remove deprecated `Flatten` and `Tile` `Op`s

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#399]
The [`Flatten`](https://github.com/pymc-devs/aesara/blob/f2ecc2e52cb704cacc1b4642fb0bf9c849bd975f/aesara/tensor/basic.py#L2859) and [`Tile`](https://github.com/pymc-devs/aesara/blob/f2ecc2e52cb704cacc1b4642fb0bf9c849bd975f/aesara/tensor/basic.py#L3090) `Op`s are deprecated and need to be removed.

**Comment by brandonwillard** [comment]
> If `Flatten` needs to be removed, does `local_flatten_lift()` in `basic_opt.py` need to be removed or changed?

Yes, anything written specifically for those `Op`s will need to be removed.

**Comment by hectormz** [comment]
I can take this issue on
