### ISSUE TITLE
Start deprecating the `aesara.gpuarray` sub-package

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#427]
The `aesara.gpuarray` is no longer maintained and due for removal.  

At the very least, we need to add a deprecation warning stating as much.  This addition might also require the removal of any automatic `aesara.gpuarray` imports, since we don't want the warning to appear unless someone actually tries to use that sub-package.

**Comment by ferrine** [comment]
Is it time for removal?

**Comment by brandonwillard** [comment]
> Is it time for removal?

Yeah, the sooner the better.
