### ISSUE TITLE
Cherry pick #408 into theano-pymc branch 

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aesara#444]
Needed for next (hopefully last) pymc3 V3 release: https://github.com/pymc-devs/pymc3/issues/4658

PR: #408

**Comment by canyon289** [comment]
Do we need to cherry pick things as this is merged into master?

**Comment by ricardoV94** [comment]
I think, we would need to create a theano-pymc branch from the commit where the last version of theano-pymc was released, and then cherry-pick it there.

**Comment by canyon289** [comment]
yep that makes sense I see whats going on now. Really appreciate the clarification

**Comment by brandonwillard** [comment]
We can't do anything for the old Theano-PyMC (e.g. we can't create new releases for it or anything similar), so I'm closing this issue until it's purpose is clear.
