### ISSUE TITLE
Fix some usability issues surrounding shared RNG objects

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#454]
Work on https://github.com/pymc-devs/pymc3/pull/4729 has highlighted a potential confusion involving `RandomStateSharedVariable`s and in-place optimizations like `random_make_inplace`.

The problem is that in-place optimizations won't be performed on `RandomStateSharedVariable`s that do not have updates specified, since they're protected by the `FunctionGraph` `Supervisor` feature set up by `aesara.compile.function.types.std_fgraph`.

In order to get around this, one can add/use the `default_update` property on the `RandomStateSharedVariable` (e.g. see [here](https://github.com/pymc-devs/pymc3/blob/53f6f43fb3b23fcc50b7b924eaa0fe89613811aa/pymc3/distributions/distribution.py#L162) and `RandomStream.gen`); however, this isn't set automatically, so it can lead to confusion.

Let's consider adding the `default_update` property automatically.  This could probably be done in `RandomVariable.make_node`, but we first need to consider whether or not this will have other repercussions/restrictions/etc.

**Comment by ricardoV94** [comment]
> whether or not this will have other repercussions/restrictions/etc.

One possible limitation concerns variable replacements, an example of which emerged here: https://github.com/pymc-devs/pymc3/pull/4903#issuecomment-893430147

Maybe we could solve it at compile ttime instead? Is it possible for a rewrite to manipulate the default_update of Shared variables?

**Comment by brandonwillard** [comment]
> Maybe we could solve it at compile time instead? Is it possible for a rewrite to manipulate the default_update of Shared variables?

That's a great question, and I'm confident that this idea will be important at some point.

One of the issues with this is that the updates are returned to the user as an object that's independent from the graph that uses the updates, so there's always the chance that users will manually specify updates when calling `aesara.function`.  I'm assuming we can ignore such updates when a graph has been rewritten to&mdash;say&mdash;remove the relevant nodes from the compiled graph.

Aside from that, I believe that updates-generating `Op`s like `Scan` can be rewritten to remove the terms that are directly associated with the corresponding updates.  For instance, `Scan`s can be refactored to remove the outer-inputs and inner graphs elements that correspond to updates; we've come across this in https://github.com/aesara-devs/aeppl/pull/24.

**Comment by brandonwillard** [comment]
Following up on a [Gitter conversation](https://gitter.im/aesara-devs/aesara?at=61d5eadb7842bd3ca92f9c58) about this, it's really the interaction between `Scan` and a special `.update` attribute that makes `RandomVariable`s work as expected within a `Scan`.  

Those attributes are added to the outputs of `RandomVariable`s by `RandomStream`, which is the main reason why the `RandomVariable`s produced by `RandomStream` work with `Scan`.  `Scan` picks up the values in that attribute and adds them to the `updates` it produces.

We need to do something so that effectively arbitrary use of shared RNG objects is possible.  For instance, we could change `Scan` so that it performs the same operations that it currently does when `.updates` is present, but without the need for a `.updates`.

That and/or we should make it very clear that `RandomStream` is _the_ interface for generating `RandomVariable` outputs.
