### ISSUE TITLE
Add the `logaddexp` function to `aesara.tensor`

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aesara#467]
The function can be easily implemented, but for the sake of getting closer to the numpy API we should add the function to `aesara.tensor`:

 https://numpy.org/doc/stable/reference/generated/numpy.logaddexp.html

**Comment by brandonwillard** [comment]
Yeah, we should add a helper function for this (e.g. [PyMC3's](https://github.com/pymc-devs/pymc3/blob/d95827f61cc101fe1701183a7b89d3ca44708af5/pymc3/math.py#L189) or [`pymc3-hmm`'s](https://github.com/AmpersandTV/pymc3-hmm/blob/ca7f86988dbb7a88e2b5f802ff3d0b2e71f6f291/pymc3_hmm/utils.py#L90)).

This is also related to #404 and #465.
