### ISSUE TITLE
Replace `aet.abs_` with `aet.abs`

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aesara#480]
The [documentation](https://aesara.readthedocs.io/en/latest/library/tensor/basic.html) does specify that `aet.abs` can be used instead of `aet.abs_` but this is actually not the case in 2.0.11.

**Comment by ricardoV94** [comment]
I read the documentation as saying `at.abs_` can be replaced by the python `abs`.

**Comment by rlouf** [comment]
Even then (I haven't tried), from a numpy user perspective I would expect `aet.abs` to work.

**Comment by ricardoV94** [comment]
Yeah, I don't know what's the reason against `at.abs`

**Comment by brandonwillard** [comment]
I'm guessing it was a naive way to avoid the name collision.

**Comment by ricardoV94** [comment]
Oh to not overwrite the python built-in?

**Comment by brandonwillard** [comment]
> Oh to not overwrite the python built-in?

Yeah, probably.

**Comment by ricardoV94** [comment]
https://stackoverflow.com/questions/45413909/should-i-use-np-absolute-or-np-abs

**Comment by rlouf** [comment]
Should I go ahead and add an alias?

**Comment by ricardoV94** [comment]
I don't see why not. We have methods with the same name as other built-ins already.

**Comment by twiecki** [comment]
Yeah, we should fix this.

**Comment by ricardoV94** [comment]
This one will probably lead to a lot of issues without a temporary deprecation warning, which I don't think was added.

**Comment by brandonwillard** [comment]
There can't be a deprecation warning until a solution to https://github.com/aesara-devs/aesara/issues/440 is in place; otherwise, this deprecation hasn't removed the old `aesara.tensor.abs_`, so there shouldn't be any issues with this change.
