### ISSUE TITLE
Test suite is not included in the tarball from PyPI

### ISSUE THREAD

**Issue by sergiopasra** [aesara-devs/aesara#494]
In the tarball from PyPI, the test directory is mostly empty, it doesn't contain any Python file. It would be nice to be able to run some tests on the released code.

**Comment by brandonwillard** [comment]
The `tests` package is intentionally excluded in [`setup.py`](https://github.com/aesara-devs/aesara/blob/main/setup.py#L59).  

As of now, you can use `pip install -e "git+https://github.com/aesara-devs/aesara.git@rel-2.0.11#egg=aesara"` to download the source&mdash;including the tests&mdash;and install the package in your local environment simultaneously.

**Comment by sergiopasra** [comment]
May I ask the rationale for this decision? 
Theano and Theano-Pymc both provide tests in the tarball from PyPI

I would like to run the tests after building a package for Fedora. The tests are useful to verify the functionality of aesara in different architectures, not only x86 but currently armv7, aarch64, s390x and ppc64le

**Comment by brandonwillard** [comment]
We have an entirely different test setup now (e.g. the old testing scripts are gone, the test package/module layout is entirely different, etc.), so comparisons with Theano[-PyMC] are no longer valid.  

We could probably include the `tests` directory in the source distribution with some minor changes to the `MANIFEST`, but that still wouldn't make things work exactly as they did in Theano[-PyMC].  Regardless, you can put in a feature request for all this.

In general, **Aesara is not guaranteed to adhere to any of the project design and development conventions of Theano[-PyMC]**.  The only thing connecting Aesara to Theano is its history and basic goal of providing a NumPy and SciPy-familiar interface.

**Comment by sergiopasra** [comment]
> We have an entirely different test setup now (e.g. the old testing scripts are gone, the test package/module layout is entirely different, etc.), so comparisons with Theano[-PyMC] are no longer valid.
> 

I understand that

> 
> > I would like to run the tests after building a package for Fedora. The tests are useful to verify the functionality of aesara in different architectures, not only x86 but currently armv7, aarch64, s390x and ppc64le
> 
> I'm not sure how that precludes the simple source install described [above](https://github.com/aesara-devs/aesara/issues/494#issuecomment-868806724).

Well, it can be done. Our workflow is not exactly as you describe, but it is possible. The thing is, we (Fedora packagers) try to get the source from PyPI first and rely on code from VCS only if that is not convenient. 

My question is, why the tests are excluded from the release?. Are they not completely functional for the moment? Can only work in a CI environment and are not expected to be run by users?
