### ISSUE TITLE
Create nightly releases

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#511]
We could really use nightly release packages.

**Comment by ricardoV94** [comment]
Anyone knows some packages we should have a look at?

**Comment by brandonwillard** [comment]
I believe @kc611 was looking into this a little while ago.

**Comment by kc611** [comment]
Was thinking something along the lines of : https://github.com/marketplace/actions/automatic-releases

**Comment by dfm** [comment]
We already have a workflow for pushing releases to PyPI, so it shouldn't be too complicated to copy that, make it triggered on a daily cron, and push to an (e.g.) `aesara-nightly` package on PyPI. I'd be happy to submit a draft PR if that would be useful, and if you think that that would do the trick.
