### ISSUE TITLE
Expose `standard_normal` in `RandomStream`.

### ISSUE THREAD

**Issue by zoj613** [aesara-devs/aesara#528]
The docs state that `RandomStream` is meant to function like `np.random.RandomState` but currently, we cannot use `standard_normal` via `RandomStream`.

```python
In [1]: from aesara.tensor.random.utils import RandomStream
   ...: 
   ...: rng = RandomStream()

In [2]: rng.standard_normal()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)

```

**Please provide the full traceback of any errors.**
```
<ipython-input-2-400cf391cbda> in <module>
----> 1 rng.standard_normal()

~/.pyenv/versions/miniconda3-4.7.12/envs/pymc3/lib/python3.9/site-packages/aesara/tensor/random/utils.py in __getattr__(self, obj)
    170 
    171         if ns_obj is None:
--> 172             raise AttributeError("No attribute {}.".format(obj))
    173 
    174         from aesara.tensor.random.op import RandomVariable

AttributeError: No attribute standard_normal.
```

**Comment by zoj613** [comment]
@brandonwillard is this a simple fix of just using:
```python
standard_normal = functools.partial(normal, loc=0.0, scale=1.0)
```
or defining a separate class
```python
class NormalRV(RandomVariable):
	...
```
?

**Comment by ricardoV94** [comment]
The partial looks fine

**Comment by zoj613** [comment]
> The partial looks fine

Maybe not. I get a `AttributeError: 'functools.partial' object has no attribute '__name__'` error running the `rv_numpy_tester` function locally.

**Comment by zoj613** [comment]
> > The partial looks fine
> 
> Maybe not. I get a `AttributeError: 'functools.partial' object has no attribute '__name__'` error running the `rv_numpy_tester` function locally. it seems like the tests rely on the structure of the objects.
