### ISSUE TITLE
Fix Numba performance issues involving `CAReduce` `Op`s

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#529]
The performance discussion in #404 demonstrates a disparity between our current C backend and Numba, with the latter not scaling as well as the former for `CAReduce` `Op`s (e.g. `max` with `axis` arguments given).

From [this discussion](https://numba.discourse.group/t/numba-performance-doesnt-scale-as-well-as-numpy-in-vectorized-max-function/782), it looks like we could generate our own `for`-loop(s) instead of using `vectorized`, if we want to get closer to C/NumPy performance with the Numba backend.  

At minimum, we need to do this for the conversion of `CAReduce` `Op`s, but it might help overall if we completely replaced [our use of `vectorized`](https://github.com/aesara-devs/aesara/blob/5248aa9ae9ab8b002b45cb78215c5772b3f25831/aesara/link/numba/dispatch.py#L450).

**Comment by brandonwillard** [comment]
For anyone who's interested, [here's](https://github.com/numpy/numpy/blob/1cc3f07ad3e0987da7d399dd8febf01ef3b48b45/numpy/lib/function_base.py#L2287) an example of how it's done by NumPy in pure Python.  We need to generate Numba-compatible Python code that essentially does the same things (e.g. compute the broadcasted inputs and output shapes, iterate over the broadcasted output shape and compute the scalar values, etc.)

**Comment by fanshi118** [comment]
> For anyone who's interested, [here's](https://github.com/numpy/numpy/blob/1cc3f07ad3e0987da7d399dd8febf01ef3b48b45/numpy/lib/function_base.py#L2287) an example of how it's done by NumPy in pure Python. We need to generate Numba-compatible Python code that essentially does the same things (e.g. compute the broadcasted inputs and output shapes, iterate over the broadcasted output shape and compute the scalar values, etc.)

How do we compute the broadcasted inputs and output shapes with the given parameters in `create_vectorize_func`? By doing `op.infer_shape()`, `node.inputs[0].shape.eval()`, or something else?

**Comment by brandonwillard** [comment]
Per [this post](https://numba.discourse.group/t/numba-performance-doesnt-scale-as-well-as-numpy-in-vectorized-max-function/782/5?u=brandonwillard), if we want to get NumPy/C-like speed, would also need to update the "cheap" pass for only **some** compiled functions (e.g. the functions generated for `CAReduce` `Op`s&#x2013;at the very least).

Here are some important points&#x2013;and a very temporary workaround&#x2013;that @gmarkall brought up during a discussion.

Let's start with an overly simple scenario involving two functions `f` and `g`:

```python
import numba


@numba.njit
def f():
    pass


@numba.njit
def g():
    pass

```

We can get to the `CPUCodegen` object, where the `_mpm_cheap` objects reside, as follows:

```python
f._compiler.targetdescr.target_context._internal_codegen._mpm_cheap
```

We could replace this object with one that has `loop_vectorize` and `slp_vectorize` set to `True`, and that would allow LLVM to apply the missing optimizations.

Unfortunately, these objects are shared across `f` and `g`, so we can't simply change one of them without affecting the other(s).

```python
assert f._compiler.targetdescr.target_context is g._compiler.targetdescr.target_context
```

However, we could *temporarily* change one of them, compile, and reset the value: e.g.

```python
context = g._compiler.targetdescr.target_context

old_pm = context._mpm_cheap
new_pm = context._module_pass_manager(loop_vectorize=True,
                                      slp_vectorize=True,
                                      opt=3,
                                      cost="cheap")
context._mpm_cheap = new_pm
# Manually compile...
context._mpm_cheap = old_pm
```

**Comment by brandonwillard** [comment]
Also, to implement our own `vectorized`, we may need https://github.com/numba/numba/pull/7119 to go through.  We can always manually add the changes from that PR in the meantime, though.

**Comment by fanshi118** [comment]
Here's a [gist](https://gist.github.com/fanshi118/8803dfe1244489e6ea95fae7b263fd38) from where we left off last time. Starting at line 56 is the custom implementation we tinkered with using a two-array example.

**Comment by twiecki** [comment]
@fanshi118 That looks very close to done, want to do a PR? Would be a great contribution.

**Comment by brandonwillard** [comment]
As a very promising alternative approach to the underlying `CAReduce`-based issues involving Numba's `vectorize` and our current graph translations, we have https://github.com/numba/numba/pull/7524.  It allows us to call the underlying NumPy C code directly (i.e. without use of Python/`objmode`).

The approach in that PR also serves as a solution to #603 and the use of `objmode` by `AdvancedSubtensor*`.
