### ISSUE TITLE
`RandomVariable` constant broadcastable is incorrect

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#536]
The broadcastable property isn't being computed correctly by `RandomVariable` in certain cases:

```python
import numpy as np

import aesara
import aesara.tensor as at


# This works
assert at.random.normal(0, 1, size=1).broadcastable == (True,)

size = at.as_tensor(1)

# This fails
assert at.random.normal(0, 1, size=size).broadcastable == (True,)
```

**Comment by ricardoV94** [comment]
Could this be behind the issue was having here: https://github.com/aesara-devs/aeppl/pull/26#discussion_r673149593

**Comment by brandonwillard** [comment]
> Could this be behind the issue I was having here: [aesara-devs/aeppl#26 (comment)](https://github.com/aesara-devs/aeppl/pull/26#discussion_r673149593) ?

Yeah, seems very likely.
