### ISSUE TITLE
Clean up `tracks` functionality

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#557]
The `tracks` option is a setting available to `LocalOptimizer`s that limits their scope of applicability to certain `Op` classes and instances.  Currently, this feature is only used in select places (e.g. `LocalMetaOptimizer` and `EquilibriumOptimizer`) and with limited capabilities (see #51).

We need to clarify the scope of this feature by either generalizing it or restricting its scope by&mdash;for example&mdash;limiting its availability to only the (global) optimizers that use it.  

Either approach would make much clearer what it does and when it's relevant.  For instance, we could reduce the amount of redundant `isinstance` checks that appear in rewrites that use `local_optimizer`.

I'm partial to the first approach (i.e. generalize and improve the `tracks` functionality).  This could be accomplished by improving the inheritance checking for composite `Op` situations (e.g. `Elemwise` `Op`s that need to be filtered based on their scalar `Op`s) and by providing an automatic `isinstance` check derived from `tracks` for the resulting `LocalOptimizer` instance.  The latter would prevent the need for redundant `tracks` + manual `isinstance` checks and it could be done in a way that allows meta/`GlobalOptimizer`s to skip the automatic check and perform their own `track`s-based filtering/applications.

**Comment by ricardoV94** [comment]
These are the relevant lines I think: https://github.com/aesara-devs/aesara/blob/5b47e32ffe3ebf052dbe3aa34183eb9bd2f35ffa/aesara/graph/opt.py#L1331-L1335

**Comment by ricardoV94** [comment]
Also worth mentioning that the Patternsub uses the first element as the `tracks` https://github.com/aesara-devs/aesara/blob/5b47e32ffe3ebf052dbe3aa34183eb9bd2f35ffa/aesara/graph/opt.py#L1676-L1680

**Comment by ricardoV94** [comment]
Copying @brandonwillard example from https://github.com/aesara-devs/aesara/pull/562#issuecomment-900618881:

> Since this has come up a few times already, here's an example that illustrates exactly how `tracks` is too restrictive and why these kinds of `tracks` changes aren't generally warranted:
```python
from copy import copy

import aesara
import aesara.tensor as at

from aesara.tensor.elemwise import Elemwise
from aesara.tensor.math_opt import get_clients

from aesara.graph.opt import out2in, local_optimizer, LocalOptGroup
from aesara.graph.opt_utils import optimize_graph
from aesara.misc.frozendict import frozendict


aesara.config.on_opt_error = "raise"


@local_optimizer([at.add])
def ps(fgraph, node):

    if not (
        isinstance(node.op, Elemwise)
        and isinstance(node.op.scalar_op, type(at.add.scalar_op))
    ):
        return

    return at.add(node.inputs[1], node.inputs[0]).owner.outputs


opt_grp = LocalOptGroup(ps)
test_opt = out2in(opt_grp, name="ps", ignore_newtrees=True)

x, y = at.vectors("xy")
z = at.add(x, y)

z_new = optimize_graph(z, [], custom_opt=test_opt)


aesara.dprint(z)
# Elemwise{add,no_inplace} [id A] ''
#  |x [id B]
#  |y [id C]

aesara.dprint(z_new)
# Elemwise{add,no_inplace} [id A] ''
#  |y [id B]
#  |x [id C]


new_add = copy(at.add)
# This can/will be changed when an `Op` is in-placed
new_add.inplace_pattern = frozendict({0: 0})

assert new_add != at.add

z = new_add(x, y)

z_new = optimize_graph(z, [], custom_opt=test_opt)

# XXX: Doesn't work, because `tracks` is too restrictive due to its use of
# `__eq__` instead of a more appropriate type-based filtering
aesara.dprint(z_new)
# Elemwise{add,no_inplace} [id A] ''
#  |x [id B]
#  |y [id C]
```

> Now, if the example rewrite _shouldn't_ be performed on in-placed subgraphs, that's a different story altogether, and `tracks` isn't a good approach for that&mdash;especially since such concerns are already covered by the `Supervisor` and `DestroyHandler` `Feature`s.  Any other concerns that have to do with the exact details of this example rewrite&mdash;or the specifics of in-placing&mdash;are irrelevant; this example demonstrates that, when `tracks` is used (which is already a big question in some caess), an `Op` instance is too restrictive for the majority of our rewrites (or quite possibly _all_ of them).

**Comment by ricardoV94** [comment]
I think there are two important points:

## First
`tracks` is supposed to provide a cheap filter on which rewrites to attempt on a graph. If a rewrite is only ever relevant to graphs with a `sigmoid` in it, then there is no point in ever calling the rewrite if no `sigmoid` node exists.

However, most of the local rewrites that use `tracks` bail out immediately via an `isinstance` check at the top. This is probably quite cheap even if called for thousands of irrelevant nodes, raising the question of whether `tracks` is that useful.

## Two
The way `tracks` is currently implemented might be too inflexible as pointed by @brandonwillard in the example above and @jeffreyenos in #550. For example we might want to apply the rewrite to subclasses of `sigmoid` (I would still like to ask for `non-inplace` example where this would be a realistic example).
