### ISSUE TITLE
Missing windows compile-chain requirements in Conda recipe: `m2w64-toolchain`

### ISSUE THREAD

**Issue by twiecki** [aesara-devs/aesara#564]
I'm surprised that `libblas`, `lapack` are not part of the dependencies.

Moreover, pymc3 listed `m2w64` as a dependency for compilation on windows, this might also need to be included here.

In an attempt to have clearer division, I'm proposing to remove these dependencies from PyMC3 https://github.com/pymc-devs/pymc3/pull/4932 and add them here. 

Related: https://github.com/conda-forge/aesara-feedstock/pull/27

**Comment by brandonwillard** [comment]
It looks like these were added recently, so I'm closing this.

**Comment by twiecki** [comment]
While these can not be added to pip requirements, I don't think they were added to the condo recipe that's in aesara. We can do that once we figure it out in https://github.com/pymc-devs/pymc3/pull/4932.

**Comment by brandonwillard** [comment]
> While these can not be added to pip requirements, I don't think they were added to the condo recipe that's in aesara. We can do that once we figure it out in [pymc-devs/pymc3#4932](https://github.com/pymc-devs/pymc3/pull/4932).

All the requirements mentioned in the original/first comment are in the Conda recipe, right?  Now, it seems like an additional one, `m2w64-toolchain`, may also be needed, or are the original ones also not working as expected?

**Comment by twiecki** [comment]
Yes that's correct.

**Comment by brandonwillard** [comment]
I believe this has been fixed by https://github.com/conda-forge/aesara-feedstock/pull/88.
