### ISSUE TITLE
`pm.sample_prior_predictive()` not working with Aesara v.2.1.3

### ISSUE THREAD

**Issue by larryshamalama** [aesara-devs/aesara#568]
`pm.sample_prior_predictive` doesn't seem to work when I upgrade Aesara to the latest version (2.1.3), but it works if I use Aesara v.2.0.12. Any ideas why this may be the case? See the example below and notebooks [here](https://github.com/larryshamalama/pymc3-playground/blob/master/notebooks/shortcomings/sample_prior_aesara_working.ipynb) and [here](https://github.com/larryshamalama/pymc3-playground/blob/master/notebooks/shortcomings/sample_prior_aesara_not_working.ipynb)

```{python}
with pm.Model() as model:
    norm = pm.Normal("normal-dist", mu=0., sigma=5.)
    
    prior = pm.sample_prior_predictive()
```

yields

```{python}
TypeError: ('Constants not allowed in param list', TensorConstant{[]})
```

**Comment by ricardoV94** [comment]
This is probably due to https://github.com/aesara-devs/aesara/pull/556

But it's likely a PyMC3 issue, with some check that has to be tweaked. Do you mind reopening the issue there?

**Comment by larryshamalama** [comment]
Of course!
