### ISSUE TITLE
Port tests to PyTest completely

### ISSUE THREAD

**Issue by ferrine** [aesara-devs/aesara#597]
There are a lot of tests that are mixed between unittests, pytest. Unifying them should benefit maintenance costs

The roadmap is to create many small PRs per file to be on the same page with main branch

**Comment by brandonwillard** [comment]
> There are a lot of tests that are mixed between unittests, pytest.

Can you clarify what these differences are, or provide some examples of what you plan on changing?  

In general, it's better to determine whether or not changes are agreeable _before_ any real work has been done.

**Comment by ferrine** [comment]
I was very confused by having classes in tests. Thats why I thought there is pytest mixed with unittest somewhere. I know they do not play well together. I've went briefly through the codebase in tests and found that unittest is not used anywhere.

**Comment by ferrine** [comment]
I'm closing the issue and opening a new one with the next step that is improving coverage
