### ISSUE TITLE
Remove gpuarray support

### ISSUE THREAD

**Issue by ferrine** [aesara-devs/aesara#604]
gpuarray is a legacy backend that we do not intend to support. In this issue I propose to do the following:

- [ ] delete the folder containing gpuarray related code
- [ ] delete all the tests that make use of gpuarray
- [ ] delete all the references of gpuarray in docs

This is a major influence on the codebase, requesting discussion

**Comment by ricardoV94** [comment]
Duplicate of #427?

**Comment by brandonwillard** [comment]
> Duplicate of #427?

Yeah.
