### ISSUE TITLE
Support `updates` option for `aesara.function` in Numba

### ISSUE THREAD

**Issue by kc611** [aesara-devs/aesara#622]
## Description of your problem or feature request

This is more of a question than an issue, do we support the symbolic inputs and updates ?

Though it seems that in this case the graph generated is 'empty' and `NumbaLinker` isn't able to handle that, so this can be a whole another issue than the above question. This shouldn't be that common a case though. 

**Please provide a minimal, self-contained, and reproducible example.**
```python
import numpy as np
import aesara
import aesara.tensor as aet
from aesara.graph.optdb import OptimizationQuery
from aesara.compile.mode import Mode
from aesara.link.numba.linker import NumbaLinker
from aesara.compile.io import In

opts = OptimizationQuery(include=[None], exclude=["cxx_only", "BlasOpt"])
numba_mode = Mode(NumbaLinker(), opts)
py_mode = Mode("py", opts)

a = aet.dscalar("a")
f = aesara.function([In(a, value=0.0, update=a + 1)], a, mode=py_mode) # Passes
f = aesara.function([In(a, value=0.0, update=a + 1)], a, mode=numba_mode) # Fails
# f = function([], [], updates=[(a, a), (b, (2 * b))]) # Also fails with same error
```

**Comment by ricardoV94** [comment]
Do we know if anything is actually missing here? For the few cases I checked it seems to be working. Or do we want a better implementation?

**Comment by brandonwillard** [comment]
It looks like the original example works, as well, so we can close this and open another issue for any remaining `updates`-related Numba issues we find.
