### ISSUE TITLE
Fix flaky RNG usage in tests

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#644]
All tests that use `tests.tensor.utils.test_rng`&mdash;and the helper functions that rely on it (e.g. `tests.tensor.utils.[random, random_nonzero, integers]`, etc.)&mdash;need to be refactor so that each individual unit test creates and uses its own RNG state from fixed seeds.

Currently, every test that relies on that RNG state is implicitly order dependent and flaky.  For example, the test results can differ when run individually, as a module, and all together, which makes localized work inconsistent and slow, because an entire run of the test suite is necessary to determine whether or not they will pass in CI.

**Comment by aerubanov** [comment]
@brandonwillard, Looks like that now ```utt.fetch_seed()``` is used and it should fix this problem https://github.com/aesara-devs/aesara/blob/a0604e5224fbfd4d4bfa804b1c3ac101cdacd52c/tests/tensor/utils.py#L250 . Is this issue still actual?

**Comment by brandonwillard** [comment]
This can probably be closed now, because I updated a lot of this recently.  At the very least, I've been able to run `pytest-xdist` for the entire test suite without issues since making those changes.

I'll close it for now and we can reopen it when we find any more cases.
