### ISSUE TITLE
Remove `TensorConstant.tag.unique_value`

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#648]
`TensorConstant.tag.unique_value` is an unnecessary specialized field used in only a few places.  This field also overlaps with the logic in `get_scalar_constant_value` and `extract_constant`, making for yet another redundancy.  Since this redundancy is attached to a core type, its removal has some priority over the other two functions.

In general, it can be easily replaced by a simple helper function&mdash;one that could also replace some of the functionality provided by `get_scalar_constant_value` and `extract_constant`, both of which are also slated for removal/replacement (see [here](https://github.com/aesara-devs/aesara/pull/643#issue-770029728)).

**Comment by Carlosbogo** [comment]
I would be glad to help with this, but I think it would be very helpful to  have a more in depth explanation on what the term "helper function" implies here.

**Comment by brandonwillard** [comment]
`Constant`s, and `TensorConstant`s by extension, hold their constant values (i.e. `np.ndarray`s) in a `Constant.data` field.  `TensorConstant.tag.unique_value` is supposed to be a scalar "reduction" of that field, so, for instance, if the field's value is a single scalar value duplicated/broadcasted in some way, `TensorConstant.tag.unique_value` will be that scalar value.

This logic is specified [here](https://github.com/aesara-devs/aesara/blob/1798404b4f727779eb1908f5e627b525dbf1d469/aesara/tensor/var.py#L970), and it can be extracted into a simple helper function with a name like `get_unique_value` and used explicitly by any logic currently depending on `TensorConstant.tag.unique_value`.

From what I can see, here are the only reference to `unique_value` in the project:
```
./aesara/scan/opt.py:169:            and node_inp.tag.unique_value is not None
./aesara/tensor/math_opt.py:135:        if getattr(v.tag, "unique_value", None) is not None:
./aesara/tensor/math_opt.py:136:            data = v.tag.unique_value
./aesara/tensor/var.py:969:        self.tag.unique_value = None
./aesara/tensor/var.py:974:                    self.tag.unique_value = flat_data[0]
./aesara/tensor/var.py:977:        if self.tag.unique_value is not None:
./aesara/tensor/var.py:978:            name = f"{self.data.shape} of {self.tag.unique_value}"
./aesara/tensor/basic.py:285:        if getattr(v.tag, "unique_value", None) is not None:
./aesara/tensor/basic.py:286:            data = v.tag.unique_value
./aesara/tensor/basic.py:299:        if getattr(v.tag, "unique_value", None) is not None:
./aesara/tensor/basic.py:300:            data = v.tag.unique_value
```
