### ISSUE TITLE
tutorials mistake?

### ISSUE THREAD

**Issue by jguerra-astro** [aesara-devs/aesara#660]
## Hello all, i was reading through the example Ops (https://aesara.readthedocs.io/en/latest/extending/extending_aesara.html) and was confused by the grad() function in the example provided below.

```python
import aesara
from aesara.graph.op import Op
from aesara.graph.basic import Apply


class AXPBOp(Op):
    """
    This creates an Op that takes x to a*x+b.
    """
    __props__ = ("a", "b")

    def __init__(self, a, b):
        self.a = a
        self.b = b
        super().__init__()

    def make_node(self, x):
        x = aesara.tensor.as_tensor_variable(x)
        return Apply(self, [x], [x.type()])

    def perform(self, node, inputs, output_storage):
        x = inputs[0]
        z = output_storage[0]
        z[0] = self.a * x + self.b

    def infer_shape(self, fgraph, node, i0_shapes):
        return i0_shapes

    def grad(self, inputs, output_grads):
        return [a * output_grads[0] + b]
```

 After asking on the pymc discourse forum It seems that this is a mistake and the grad function should be

```python
    def grad(self, inputs, output_grads):
        return [self.a * output_grads[0]]
```

**Comment by kc611** [comment]
Hey, @jguerra-astro seems like you're right. This is an documentation error. 

Would you be interested in opening a PR for this fix ? 

The exact file you'll be looking to change will be: https://github.com/aesara-devs/aesara/blob/main/doc/extending/extending_aesara.rst

**Comment by jguerra-astro** [comment]
sure, will do!
