### ISSUE TITLE
`RandomVariable`s fail in Numba mode due to default `Generator`s

### ISSUE THREAD

**Issue by kc611** [aesara-devs/aesara#662]
## Description of your problem or feature request

```python
import aesara  
aesara.config.mode = "NUMBA"  
import aesara.tensor as at  

at.random.normal().eval()  # Fails
```

```python
import aesara  
aesara.config.mode = "NUMBA"  
import aesara.tensor as at  

rng = np.random.RandomState()
at.random.normal(rng=rng).eval()  # Works
```

Any user will try the first implementation which will inevitably fail until Numba implements support for Numpy's `Generator`s. We should be informing the users to use the `RandomState` API whenever working with Numba backend. Alternatively, we can some implicit conversion for `Generator` to Numba's internal state array conversion similar to how we do with `RandomState`s

https://github.com/aesara-devs/aesara/blob/7c32fc48cc971889242c8a124ea577d8618f0ef2/aesara/link/numba/dispatch/random.py#L25-L30

**Comment by brandonwillard** [comment]
> Alternatively, we can some implicit conversion for `Generator` to Numba's internal state array conversion similar to how we do with `RandomState`s

This sounds more appealing.

**Comment by brandonwillard** [comment]
This issue is superseded by https://github.com/aesara-devs/aesara/issues/814.
