### ISSUE TITLE
`aesara.tensor.slinalg.Solve` doesn't match SciPy's `solve`

### ISSUE THREAD

**Issue by fshart** [aesara-devs/aesara#668]
## Change to aet.slinalg.Solve.perform to remove currently existing bug
The following mwe 
```python
import aesara.tensor as aet
import aesara
import numpy
import numpy as np


def main():
    b_dev = aet.matrix('b_dev')
    M_dev = aet.matrix('M_dev')
    sym_solve = aet.slinalg.Solve(assume_a='sym')
    sym_solve = sym_solve(M_dev, b_dev)
    sym_solve = aesara.function(
        inputs=[M_dev, b_dev],
        outputs=sym_solve,
    )
    Hc = numpy.array([[1, 0, 0], [0, 1, 1], [0, 1, 0]])
    g = numpy.array([[1], [1], [1]])
    dz = sym_solve(Hc, g)


if __name__ == "__main__":
    main()
```
results in an error
```python
 AESARA_FLAGS='exception_verbosity=high' python mwe_solve.py 
Traceback (most recent call last):
  File "*/lib/python3.9/site-packages/aesara/compile/function/types.py", line 976, in __call__
    self.fn()
  File "*/lib/python3.9/site-packages/aesara/graph/op.py", line 500, in rval
    r = p(n, [x[0] for x in i], o)
  File "*/lib/python3.9/site-packages/aesara/tensor/slinalg.py", line 317, in perform
    rval = scipy.linalg.solve_triangular(
  File "*/lib/python3.9/site-packages/scipy/linalg/basic.py", line 361, in solve_triangular
    raise LinAlgError("singular matrix: resolution failed at diagonal %d" %
numpy.linalg.LinAlgError: singular matrix: resolution failed at diagonal 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "**/mwe_solve.py", line 22, in <module>
    main()
  File "**/mwe_solve.py", line 18, in main
    dz = sym_solve(Hc, g)
  File "*/lib/python3.9/site-packages/aesara/compile/function/types.py", line 989, in __call__
    raise_with_op(
  File "*/lib/python3.9/site-packages/aesara/link/utils.py", line 526, in raise_with_op
    raise exc_value.with_traceback(exc_trace)
  File "*/lib/python3.9/site-packages/aesara/compile/function/types.py", line 976, in __call__
    self.fn()
  File "*/lib/python3.9/site-packages/aesara/graph/op.py", line 500, in rval
    r = p(n, [x[0] for x in i], o)
  File "*/lib/python3.9/site-packages/aesara/tensor/slinalg.py", line 317, in perform
    rval = scipy.linalg.solve_triangular(
  File "*/lib/python3.9/site-packages/scipy/linalg/basic.py", line 361, in solve_triangular
    raise LinAlgError("singular matrix: resolution failed at diagonal %d" %
numpy.linalg.LinAlgError: singular matrix: resolution failed at diagonal 2
Apply node that caused the error: Solve{assume_a='sym', lower=False, check_finite=True}(M_dev, b_dev)
Toposort index: 0
Inputs types: [TensorType(float64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(3, 3), (3, 1)]
Inputs strides: [(24, 8), (8, 8)]
Inputs values: ['not shown', array([[1.],
       [1.],
       [1.]])]
Inputs type_num: [12, 12]
Outputs clients: [['output']]

Backtrace when the node is created (use Aesara flag traceback__limit=N to make it longer):
  File "**/mwe_solve.py", line 22, in <module>
    main()
  File "**/mwe_solve.py", line 11, in main
    sym_solve = sym_solve(M_dev, b_dev)

Debug print of the apply node: 
Solve{assume_a='sym', lower=False, check_finite=True} [id A] <TensorType(float64, matrix)> ''   
 |M_dev [id B] <TensorType(float64, matrix)>
 |b_dev [id C] <TensorType(float64, matrix)>

Storage map footprint:
 - M_dev, Input, Shape: (3, 3), ElemSize: 8 Byte(s), TotalSize: 72 Byte(s)
 - b_dev, Input, Shape: (3, 1), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 TotalSize: 96 Byte(s) 0.000 GB
 TotalSize inputs: 96 Byte(s) 0.000 GB
```
where * is the path to the environment and ** the path to the mwe.

The matrix Hc is symmetric and non-degenerate, but has a zero on the main diagonal (and is negative definite).

I traced the error to the definition of aet.slinalg.Solve.perform, and the usage of 
```python
 rval = scipy.linalg.solve_triangular(
                A,
                b,
                lower=self.lower,
                check_finite=self.check_finite,
                # trans=trans
            )
```
directly on Hc and g gave the same error. Permuting the matrix, i.e. changing the position of the zero on the diagonal, corresponded to a change in the position where the function failed
```python
numpy.linalg.LinAlgError: singular matrix: resolution failed at diagonal 1
```

Shortening the whole perform function to
```python
    def perform(self, node, inputs, output_storage):
        A, b = inputs
        output_storage[0][0] = scipy.linalg.solve(
            A,
            b,
            assume_a=self.assume_a,
            lower=self.lower,
            check_finite=self.check_finite,
            # transposed=self.transposed,
        )
```
solved the error.

## Versions and main components

* Aesara version: 2.2.6
* Python version: 3.9.7
* How did you install Aesara: pip

**Comment by brandonwillard** [comment]
The example creates an `Op` for a symmetric solver, but the matrix passed to it is not symmetric, and, when its upper diagonal is taken, the resulting triangular matrix is singular, so the error(s) appear to be reasonable.

**Comment by fshart** [comment]
> The example creates an `Op` for a symmetric solver, but the matrix passed to it is not symmetric, and, when its upper diagonal is taken, the resulting triangular matrix is singular, so the error(s) appear to be reasonable.
> 
> If you create the `Op` with `assume_a="gen"` it should use the non-triangular solver.

The matrix
1 0 0
0 1 1
0 1 0
is obviously symmetric. If the "sym" option is used to signify a triangular part of an symmetric (positive definite) matrix, then the convention of aesara is misleading.
Furthermore, the naming convention would differ from the naming convention of the underlying scipy module, since 
```python
# self.assume_a = "sym" 
scipy.linalg.solve(
            A,
            b,
            assume_a=self.assume_a,
            lower=self.lower,
            check_finite=self.check_finite,
            # transposed=self.transposed,
        )
```
handles the input correclty (and differs from the general solver for self.assume_a = "gen" ).

**Comment by brandonwillard** [comment]
Sorry, I misread the matrix, but that doesn't change the fact that it's upper triangular portion is singular and, since the triangular solver is being used, there doesn't appear to be a bug. 

Yes, the naming convention is not good, but, as I recall, use of the triangular solver is a hold-over from Theano, so we can't simply remove it entirely. We can change this issue to a request to rename the `Op` and split the triangular solver into its own `Op`.

**Comment by fshart** [comment]
The problem originally ocured in porting https://github.com/jkaardal/pyipm from Theano-PYMC by replacing 
```python
sym_solve = T.slinalg.Solve(A_structure='symmetric')
```
with
```python
sym_solve = aet.slinalg.Solve(assume_a='sym')
```
Thus there seems to be a difference somewhere between Theano, Theano-PYMC and Aesara in handling this case.

**Comment by brandonwillard** [comment]
> Thus there seems to be a difference somewhere between Theano, Theano-PYMC and Aesara in handling this case.

Yes, Theano had its own convention for specifying the form of the matrix, which only covered upper and lower triangular matrices with `solve_triangular` and plain `solve`.  It's probably better if we add a distinct `Op` for `solve_triangular` and make `Solve` correspond directly to `solve`

**Comment by fshart** [comment]
I implemented the required changes for the split including extended tests for this Issue and changes to the deprecated 
```python
solve_lower_triangular
solve_upper_triangular
```
in my branch (https://github.com/fshart/aesara) and ran pre-commit.

Since the full test only returned the Errors of Issue #477 and pre-commit passed, how do i queue my changes for review/merge?

**Comment by brandonwillard** [comment]
> Since the full test only returned the Errors of Issue #477 and pre-commit passed, how do i queue my changes for review/merge into the main branch?

Put in a PR and we'll take a look at the error(s).

**Comment by fshart** [comment]
Thanks.
Here is the PR: https://github.com/aesara-devs/aesara/pull/676
