### ISSUE TITLE
Your cuDNN version is more recent than Theano

### ISSUE THREAD

**Issue by probit2011** [aesara-devs/aesara#705]
I have been trying to enable CUDA to run PyMC3 with the assistance of the GPU. Here are the specs of the machine/software I have been using:

Windows 10
Visual Studio Community 2019
Python 3.8.12
CUDA 10.2 (I tried 11.2 before that and obtained the same problem)
CuDNN 7.6.5 (I tried 8.1 with CUDA 11.2 and obtained the same problem)
TensorFlow 2.7.0
Theano-PyMC 1.1.2
Aesara 2.3.2 (the successor to Theano)
PyMC3 3.11.4
MKL 2.4.0
For the proper installation of Theano and CUDA in a Windows environment, I followed the advice provided on these web pages:

https://gist.github.com/ElefHead/93becdc9e99f2a9e4d2525a59f64b574

https://towardsdatascience.com/installing-tensorflow-with-cuda-cudnn-and-gpu-support-on-windows-10-60693e46e781

I have tested the installation against Tensorflow and it works. I have also used the tests provided on the Theano and Aesara "Read the Docs" sites (https://aesara.readthedocs.io/en/latest/tutorial/using_gpu.html#testing-the-gpu) and ran the check_blas test provided with Theano/Aesara (https://raw.githubusercontent.com/Theano/Theano/master/theano/misc/check_blas.py). After all this, I still get these disappointing error/warning messages:

`WARNING (aesara.tensor.blas): Using NumPy C-API based implementation for BLAS functions.`

`UserWarning: Your cuDNN version is more recent than Aesara. If you encounter problems, try updating Aesara or downgrading cuDNN to a version >= v5 and <= v7`
even though I have already downgraded cuDNN to 7.6.5 (and, obviously, can't use the GPU with Theano/Aesara/PyMC3).

With respect to the BLAS warning, I tried setting the blas__ldflags (Aesara) or blas.ldflags (Theano) as environment variables, assigning them the recommended MKL flags `-lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lguide -liomp5 -lmkl_mc -lpthread`, still nothing works.

Can anybody please help me address these two issues?

**Comment by brandonwillard** [comment]
PyMC3 does not use Aesara; however, the next version will.

You also have potentially conflicting package requirements due to `theano-pymc` and `aesara` being together in the same environment.

We have an existing issue open for MKL support with Conda on Windows: #641.

Otherwise, Aesara does not actively support the old Theano GPU code.  We are refactoring the backend and will ultimately replace nearly all of the old GPU code.
