### ISSUE TITLE
Create a `RandomState` `Variable` constructor `Op`

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#739]
We need an `Op` that will construct `RandomState` `Variable`s with the seed values as inputs.  

We should need only one such `Op` that handles all `RandomState` types (e.g. by having a fixed `Op`-level property that determines which types the `Op` generates).

This&mdash;combined with #738&mdash;will largely remove the need to use shared variables for RNG states.

**Comment by ricardoV94** [comment]
I like that approach. It sounds a lot like what we ended up doing here manually with shared RandomState variables: https://github.com/pymc-devs/pymc/blob/b29124bc054c47ca2de99789d9894db0caa17c13/pymc/initial_point.py#L200-L219

**Comment by brandonwillard** [comment]
> I like that approach. It sounds a lot like what we ended up doing here manually with shared RandomState variables: https://github.com/pymc-devs/pymc/blob/b29124bc054c47ca2de99789d9894db0caa17c13/pymc/initial_point.py#L200-L219

Another way to put it: we need an `Op` for `numpy.random.default_rng`.

**Comment by kc611** [comment]
Took a stab at this and ran into an obvious problem. How do we return a symbolic representation of a `SharedVariable` in the `Op.make_node` without providing it a value in `Op.make_node` itself ?

**Comment by brandonwillard** [comment]
> Took a stab at this and ran into an obvious problem. How do we return a symbolic representation of a `SharedVariable` (`RandomStateSharedVariable`s in this case) in the `Op.make_node` without providing it a value in `Op.make_node` itself ?

There are no shared variables in this case.

**Comment by kc611** [comment]
Do we return `Variable` that can contain/return `RandomState` symbolically?

I am having trouble understanding how such an `Op` will be made with current `Variable` classes.

**Comment by brandonwillard** [comment]
Yeah, a plain `Variable` can be used, but it might be better to have a specific variable type.  That would make it possible to do type checking on the variable instances instead of their `.type` class attributes.
