### ISSUE TITLE
Add `aesara.as_symbolic` to the documentation

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#746]
#743 introduced an `aesara.as_symbolic` dispatch function that converts any Python object into its symbolic Aesara equivalent.  We should add this information to the documentation somewhere.

**Comment by rlouf** [comment]
@anirudhacharya asks:

> I would also like to add this https://github.com/aesara-devs/aesara/issues/746 in this PR itself. Can someone point me where in the documentation the as_symbolic function might go, would it be here - https://github.com/aesara-devs/aesara/blob/main/doc/library/graph/graph.rst

Originally posted in https://github.com/aesara-devs/aesara/pull/1262#issuecomment-1279930205

**Comment by rlouf** [comment]
My first thought would be to add it to the [API documentation main page](https://aesara.readthedocs.io/en/latest/library/index.html) as it is a general functionality available in the `aesara` namespace.
