### ISSUE TITLE
Remove primers/documentation for external packages

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#750]
We can't afford to write or maintain documentation for external libraries like NumPy or even Python itself&mdash;no matter how big or small the material may be.  

The two most egregious instances comprise the entirety of [the "Prerequisites" section in the tutorial](https://aesara.readthedocs.io/en/latest/tutorial/index.html#prerequisites).  

We should remove those and any other similar pages/sections and simply focus the documentation for the system we're developing.

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this.
Just to be sure, is the idea to just remove completely the section you mentioned from the documentation and anything else that I can find whose focus is on explaining anything that doesn't belong to this project?

**Comment by brandonwillard** [comment]
> Hi, I would like to work on this. 

Sound great; thanks!

> Just to be sure, is the idea to just remove completely the section you mentioned from the documentation and anything else that I can find whose focus is on explaining anything that doesn't belong to this project?

Yes, the section I mentioned definitely needs to be removed, and we can discuss anything else you find in the PR.
