### ISSUE TITLE
Remove "Requirements" and "Updating Aesara" sections from the documentation

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#753]
The ["Requirements"](https://aesara.readthedocs.io/en/latest/requirements.html) section is largely out of date, unnecessary, and not worth maintaining, so we should remove it.

Information regarding the installation requirements should be in the ["Installing Aesara"](https://aesara.readthedocs.io/en/latest/install.html) section, especially since the requirements will depend almost exclusively on what and how Aesara is installed.

Likewise, any useful information in ["Updating Aesara"](https://aesara.readthedocs.io/en/latest/updating.html#updating-aesara) should be moved to "Installing Aesara" and provided as additional information under each of the relevant installation scenarios.

**Comment by adil14788** [comment]
Can I work on this issue?

**Comment by brandonwillard** [comment]
> Can I work on this issue?

By all means!

**Comment by redlif345** [comment]
hii i really want to contribute on this issue can i?

**Comment by adil14788** [comment]
Hey @brandonwillard,
I am not able to rebuild the documentation. I facing an issue in setting up the development environment.
Can you please help me ??

**Comment by SaarthakMaini** [comment]
Is this issue still open. I am new to open source and would love to contribute

**Comment by brandonwillard** [comment]
> Hey @brandonwillard, I am not able to rebuild the documentation. I facing an issue in setting up the development environment. Can you please help me ??

Let's discuss this in the PR.

**Comment by brandonwillard** [comment]
> hii i really want to contribute on this issue can i?

> Is this issue still open. I am new to open source and would love to contribute

@redlif345 and @SaarthakMaini, thank you both for the interest!  If you're viewing this in the browser, the menu on the right indicates that this issue already has a linked PR (i.e. https://github.com/aesara-devs/aesara/pull/754), so it would be best to attempt another issue instead, since we will generally only be able to review one PR for an issue at a time.

If you want to find another issue, select the tags "help wanted", "good first issue", and/or any other ones that fit your interests.

Also, either before or after finding an issue, be sure to read and follow the instructions in [the developer start guide](https://aesara.readthedocs.io/en/latest/dev_start_guide.html#developer-start-guide).
