### ISSUE TITLE
Continue cleaning up the sparse/dense tensor types

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aesara#886]
Currently, `TensorType`s aren't an abstract class, and direct instances of `TensorType`s represent dense tensors, as do instances of the new `DenseTensorType`.

Instead, it would be better to have and use a single abstract tensor `Type` and distinct sparse and dense tensor `Type`s.  In this case, we could remove all the meta classes.

One of the issues I can see with this change: external libraries that use `TensorType` and/or `TensorVariable`s directly will need to change these to `DenseTensorType` and `DenseTensorVariable`, unless we continue to keep these names reserved for dense tensors and use new `AbstractTensor[Type|Variable]` classes as the shared base.

_Originally posted by @brandonwillard in https://github.com/aesara-devs/aesara/pull/766#pullrequestreview-894459515_

**Comment by ricardoV94** [comment]
Sounds less painful to keep the current `TensorType` as is and add the new abstract class

**Comment by rlouf** [comment]
> Sounds less painful to keep the current `TensorType` as is and add the new abstract class

I agree, and although `DenseTensorType` is more explicit I think it would confuse most people. Everyone is used to "dense" being the default.

**Comment by brandonwillard** [comment]
Yeah, we can make `Tensor[Type|Variable]` aliases for `DenseTensor[Type|Variable]` and remove all uses of `Tensor[Type|Variable]` from internal code.  That should clear things up a lot.

**Comment by danhphan** [comment]
Hi, I can work on this task. Thanks

**Comment by brandonwillard** [comment]
> Hi, I can work on this task. Thanks

That would be great!
