### ISSUE TITLE
Intel MKL FATAL ERROR upon importing Aesara on M1 Mac 

### ISSUE THREAD

**Issue by larryshamalama** [aesara-devs/aesara#909]
Importing Aesara yields the following error due to the `mkl` package.

<img width="833" alt="Screen Shot 2022-04-16 at 4 18 04 PM" src="https://user-images.githubusercontent.com/24764859/163692568-f5603d45-39be-455a-ba3a-4603eb7f92d7.png">

Recreating the conda environment in [`environment.yml`](https://github.com/aesara-devs/aesara/blob/main/environment.yml) minus the [`mkl` dependencies](https://github.com/aesara-devs/aesara/blob/main/environment.yml#L20-L22) allows Aesara to be imported.

Given that `mkl` is an optional dependency, its removal altogether can be considered. Another option would be to replace it by [blip](https://github.com/flame/blis) as suggested by @dgerlanc 

CC @brandonwillard 

* Aesara version: 2.4.0
* Python version: 3.10.4
* Operating system: Mac Monterey (M1)
* How did you install Aesara: conda

**Comment by dgerlanc** [comment]
@brandonwillard We may want to add an `environment-arm.yml` without the `mkl` dependencies.

**Comment by dgerlanc** [comment]
I'm thinking we probably want to avoid importing `MKL` at all on ARM Mac if we're getting this failure on import.

**Comment by twiecki** [comment]
Is MKL a dependency? I thought I had removed it from conda-forge et al. In any case, it definitely should be optional

**Comment by brandonwillard** [comment]
This was effectively closed by https://github.com/aesara-devs/aesara/pull/960, but we can still do something about the error message/warning.
