### ISSUE TITLE
Bug in formatting of generated JAX code files.

### ISSUE THREAD

**Issue by jhrcook** [aesara-devs/aesara#971]
## Description of your problem or feature request

I am trying to sample from a hierarchical model using the Numpyro JAX backend, but get a funny error for some models. To begin, I have sampled successfully from other models, so the JAX backend is working fine. Unfortunately, because of the problem discussed [here](https://discourse.pymc.io/t/pymc-4-0-0b6-module-jax-ops-has-no-attribute-index-update/9267), I have had to downgrade my version of `jax` to v0.2.28 (and consequently `jaxlib` to v0.3.0). I would hope that updating `jax` would fix this problem, but it’s not an option yet.

Here is the error message I receive when trying to sample using Numpyro:

```
Traceback (most recent call last):

  File /usr/local/Caskroom/miniconda/base/envs/bluishred/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3397 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Input In [77] in <cell line: 1>
    m9_trace = model_fitting_pipeline(

  Input In [8] in model_fitting_pipeline
    trace = sample_model(

  File ~/Developer/haigis-lab/bluishred/bluishred/model_fitting.py:104 in sample_model
    trace = _sample_model(m, sample_kwargs, mcmc_backend)

  File ~/Developer/haigis-lab/bluishred/bluishred/model_fitting.py:37 in _sample_model
    trace = sample_numpyro_nuts(**sample_kwargs)

  File /usr/local/Caskroom/miniconda/base/envs/bluishred/lib/python3.10/site-packages/pymc/sampling_jax.py:483 in sample_numpyro_nuts
    logp_fn = get_jaxified_logp(model, negative_logp=False)

  File /usr/local/Caskroom/miniconda/base/envs/bluishred/lib/python3.10/site-packages/pymc/sampling_jax.py:106 in get_jaxified_logp
    logp_fn = get_jaxified_graph(inputs=model.value_vars, outputs=[model_logpt])

  File /usr/local/Caskroom/miniconda/base/envs/bluishred/lib/python3.10/site-packages/pymc/sampling_jax.py:99 in get_jaxified_graph
    return jax_funcify(fgraph)

  File /usr/local/Caskroom/miniconda/base/envs/bluishred/lib/python3.10/functools.py:889 in wrapper
    return dispatch(args[0].__class__)(*args, **kw)

  File /usr/local/Caskroom/miniconda/base/envs/bluishred/lib/python3.10/site-packages/aesara/link/jax/dispatch.py:669 in jax_funcify_FunctionGraph
    return fgraph_to_python(

  File /usr/local/Caskroom/miniconda/base/envs/bluishred/lib/python3.10/site-packages/aesara/link/utils.py:791 in fgraph_to_python
    fgraph_def = compile_function_src(

  File /usr/local/Caskroom/miniconda/base/envs/bluishred/lib/python3.10/site-packages/aesara/link/utils.py:609 in compile_function_src
    mod_code = compile(src, filename, mode="exec")

  File /var/folders/r4/qpcdgl_14hbd412snp1jnv300000gn/T/tmpilbd79jk:14
    9 9]})
    ^
IndentationError: unexpected indent
```

And here is the head of the file `/var/folders/r4/qpcdgl_14hbd412snp1jnv300000gn/T/tmpilbd79jk`:

```python
def jax_funcified_fgraph(mu_mu_a, sigma_mu_a_log_, mu_a, sigma_a_log_, delta_a, sigma_b_log_, b, sigma_c_log_, c, sigma_d_log_, delta_d, sigma_k_log_, k, alpha_log_):
    # AdvancedSubtensor1(k, TensorConstant{[0 0 0 0 0..9 9 9 9 9]})
    auto_1195180 = subtensor(k, auto_1144647)
    # Elemwise{exp,no_inplace}(sigma_d_log__)
    auto_1192542 = exp(sigma_d_log_)
    # AdvancedSubtensor1(c, TensorConstant{[0 0 0 0 0..9 9 9 9 9]})
    auto_1195178 = subtensor1(c, auto_1144647)
    # AdvancedSubtensor(b, TensorConstant{[0 0 0 0 0..9 9 9 9 9]}, TensorConstant{[0 0 0 0 0..1 1 1 1 1]})
    auto_1192551 = subtensor2(b, auto_1144647, auto_1144655)
    # Elemwise{exp,no_inplace}(sigma_a_log__)
    auto_1192553 = exp(sigma_a_log_)
    # AdvancedSubtensor1(mu_a, TensorConstant{[0 0 0 0 1.. 9 9
     9 9]})
    auto_1195177 = subtensor3(mu_a, auto_1144172)
    # Elemwise{exp,no_inplace}(alpha_log__)
    auto_1192534 = exp(alpha_log_)
    # Elemwise{exp,no_inplace}(sigma_k_log__)
```

I have tried to reproduce the error with a minimal, self-contained, reproducible example, but am unable to replicate the error. Still, it was recommended to me to open an Issue to make the devs aware of the problem. Because of this limitation, I am willing to provide as much additional information as requested.

## Versions and main components

* Aesara version: 2.6.2
* Aesara config (`python -c "import aesara; print(aesara.config)"`)
* PyMC version: 4.0.0b6 
* jax version: 0.2.28
* jaxlib version:  0.3.0
* Python version: 3.10.4
* Operating system: macOS Monterey v12.3.1
* How did you install Aesara: `conda`

**Comment by brandonwillard** [comment]
We need some means of reproducing this issue, because, via the source code alone, I'm not sure how such a formatting error could arise, especially since similar (vector) `Constant` objects appears to be printed without issue multiple times before the error line.

My only guess is that `[Tensor]Constant.__str__` is unexpectedly producing something with newlines.  We can put in a PR that addresses this universally (e.g. forcibly removes all newlines from the comment lines).

**Comment by ricardoV94** [comment]
@jhrcook Do you mind trying to use your model with the latest released Aesara version to confirm your original issue has been fixed?

**Comment by jhrcook** [comment]
> We need some means of reproducing this issue, because, via the source code alone, I'm not sure how such a formatting error could arise, especially since similar (vector) `Constant` objects appears to be printed without issue multiple times before the error line.
> 
> My only guess is that `[Tensor]Constant.__str__` is unexpectedly producing something with newlines. We can put in a PR that addresses this universally (e.g. forcibly removes all newlines from the comment lines).

I completely understand and was originally hesitant in opening an Issue because of the limited information I could provide. Thank you for suggesting a fix and applying it nonetheless.

> @jhrcook Do you mind trying to use your model with the latest released Aesara version to confirm your issue has been fixed?

Looks like it worked! Thank you both so much, this made my day!
